title: My Personal Webpage
description: >- # this means to ignore newlines until "baseurl:"
  My personal webpage hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hypnus1803.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# # Include the _data directory
# include:
#   - _data

# # Exclude from processing
# exclude:
#   - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor
#   - .gitignore
#   - .gitmodules
#   - .sass-cache
#   - .jekyll-cache
#   - .jekyll-metadata
#   - .DS_Store
#   - .vscode
#   - .vscodeignore
#   - .vscode/settings.json
#   - .vscode/tasks.json
#   - .vscode/launch.json

# # Plug-ins
# plugins:
#   - jekyll-archives
#   - jekyll-email-protect
#   - jekyll-feed
#   - jekyll-get-json
#   - jekyll-imagemagick
#   - jekyll-jupyter-notebook
#   - jekyll-link-attributes
#   - jekyll-minifier
#   - jekyll-paginate-v2
#   - jekyll-regex-replace
#   - jekyll/scholar
#   - jekyll-sitemap
#   - jekyll-tabs
#   - jekyll-toc
#   - jekyll-twitter-plugin
#   - jemoji

# jekyll_get_json:
#   - data: resume
#     json: content/resume.json # it can also be an url
# jsonresume:
#   - basics
#   - work
#   - education
#   - publications
#   - projects
#   - volunteer
#   - awards
#   - certificates
#   - skills
#   - languages
#   - interests
#   - references